name: Compile vterron.xyz/hackers Beamer slides to PDF

on: [push]

jobs:
  build_job:
    name: Build PDF slides
    runs-on: ubuntu-latest

    steps:
      - name: Git repository checkout
        uses: actions/checkout@v2

      - name: LaTeX compilation
        uses: dante-ev/latex-action@master
        with:
          root_file: sed-hackers.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: slides-pdf
          path: sed-hackers.pdf

  upload_job:
    name: Upload PDF slides
    needs: build_job
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: slides-pdf

      - name: Upload PDF slides to Amazon S3
        run: |
          aws s3 cp sed-hackers.pdf ${{ secrets.AWS_S3_BUCKET }}
